baseurl = "/"
languageCode = "en-us"
title = "Scott Barr"

theme = "hyde"

menu = "main"

[params]
  description = "Loves building awesome systems to solve interesting business problems, with Ruby, Python, Golang and Javascript. Coffee fuelled trouble machine."
